update/components/new-cta
markmead/hyperui pull request #116
Opened 2022-07-07 17:01 UTC by worawutbat

This PR adds a new CTA component.

2022-07-08 06:49 UTC, markmead requested changes
Looks awesome, few things to clean up!

Apologies as most of the comments are things I need to fix on the other CTA components.

2022-07-08 06:49 UTC, markmead commented on public/components/ctas/8.html
> +<aside class="relative overflow-hidden text-gray-300 bg-gray-900 lg:flex justify-center">
Classes that are not needed:

- `relative`
- `overflow-hidden`
- `lg:flex`
- `justify-center`

2022-07-08 06:49 UTC, markmead commented on public/components/ctas/8.html
> +    <div class="w-full p-12 text-center lg:w-2/3 sm:p-16 lg:p-24">
Not a fan of `w-full lg:w-2/3`. The child element uses `max-w-xl` so why are these needed?

2022-07-08 06:49 UTC, markmead commented on public/components/ctas/8.html
> +      <div class="max-w-xl mx-auto lg:ml-0">
Adding `lg:ml-0` here is causing you to need the `lg:flex justify-center` on the root element for this component.

Removing the previous classes highlighted and `lg:ml-0` solves that.

2022-07-08 06:49 UTC, markmead commented on public/components/ctas/8.html
> +        <div class="p-2 border inline-block">community</div>
Not a fan of having content without any inner markup within a `<div>`.

Replace with a `<span>` or a `<strong>`, your choice.

2022-07-08 06:49 UTC, markmead commented on public/components/ctas/8.html
> +        <p class="mt-4 text-2xl font-bold text-white sm:text-3xl w-2/3 text-center mx-auto">
Classes that are not needed:

- `w-2/3`
- `text-center`
- `mx-auto`

Should be a heading element, possibly a `<h2>`.

2022-07-08 06:49 UTC, markmead commented on public/components/ctas/8.html
> +        <p class="hidden lg:mt-4 lg:block mx-auto">
Don't need the `mx-auto`.

2022-07-08 06:49 UTC, markmead commented on public/components/ctas/8.html
> +        <a
Could the `href=""` be replaced with `href="#"`?

Should `text-black` be `text-gray-900` so it pairs up nicely with the background color?

How does `hover:bg-yellow-400` look? And can we add `transition` to the classes for a smooth hover effect.

2022-07-08 06:49 UTC, markmead commented on public/components/ctas/8.html
> +        <a
Probably want to consider `focus:` styling as well.

2022-07-08 14:23 UTC, markmead commented
Pushed up a fix to the PR as it was using an old version of HyperUI.

2022-07-13 09:14 UTC, markmead commented
Any update on this? Only a few small changes and then we can get this merged in! 🚀 @worawutbat

2022-07-13 14:13 UTC, worawutbat commented
> Any update on this? Only a few small changes and then we can get this merged in! 🚀 @worawutbat

i fixed this PR by your suggestion, and already to merge and thank for your suggestion and review in this PR

2022-07-13 14:29 UTC, markmead commented
Thanks @worawutbat! 🥳 

It looks like you've updated `public/components/ctas/8.html`, but the file should be `public/components/marketing-ctas/11.html`.

I've moved over your work and updated the component to match the new CTA markup, I just need you to apply those fixes to the new file and we're can ship it 🚢

2022-07-15 06:34 UTC, markmead requested changes

2022-07-15 06:34 UTC, markmead commented on public/components/ctas/8.html
> +<aside
This file shouldn't be here.

2022-07-15 06:34 UTC, markmead commented on public/components/marketing-ctas/11.html
> +<aside
Changes should be made to this file.

2022-07-16 14:14 UTC, worawutbat commented on public/components/marketing-ctas/11.html
> +<aside
My bad, Thanks @markmead

2022-07-18 07:23 UTC, markmead commented on public/components/ctas/8.html
> +<aside class="relative overflow-hidden text-gray-300 bg-gray-900 lg:flex justify-center">
Oops, this hasn't been addressed @worawutbat

2022-07-18 07:23 UTC, markmead requested changes
Can't approve this while there's feedback waiting to be addressed.

Also, you've made everything a `<strong>` now which isn't correct.

2022-07-20 15:30 UTC, markmead requested changes
Why is there now an image? This isn't the original component you asked me to review.

2022-07-20 16:09 UTC, worawutbat commented on public/components/marketing-ctas/11.html
> +      <div class="p-2 border inline-block">community</div>
> Why is there now an image? This isn't the original component you asked me to review.

sorry, i pushed PRs with wrong commit that trying to use new bg classname.

2022-07-21 07:32 UTC, markmead requested changes
You're still not understanding what needs to be done.

Sorry, but I'll review this PR one more time, if there are still issues with the HTML then I will be closing it. I'd suggest you take a look at semantic HTML.

2022-07-21 07:32 UTC, markmead commented on public/components/marketing-ctas/11.html
> +  <strong class="p-12 text-center max-w-xl sm:p-16 lg:p-24 text-gray-300">
Not a `<strong>` tag.

2022-07-21 07:32 UTC, markmead commented on public/components/marketing-ctas/11.html
> +    <strong class="max-w-xl mx-auto">
Not a `<strong>` tag.

2022-07-24 14:59 UTC, worawutbat commented
> You're still not understanding what needs to be done.
> 
> Sorry, but I'll review this PR one more time, if there are still issues with the HTML then I will be closing it. I'd suggest you take a look at semantic HTML.

Thanks for your suggestion, I fixed this PR by using the right semantic HTML.

2022-07-25 06:38 UTC, markmead requested changes
Still, work to be done, I'm closing this PR as it's been through too many revisions. Please do finish it off based on **all** the feedback provided in this PR and submit again! 🎉

2022-07-25 06:38 UTC, markmead commented on public/components/marketing-ctas/11.html
> +  class="relative justify-center overflow-hidden text-gray-300 bg-gray-900 lg:flex"
Unused classes have still not been removed.

2022-07-25 06:38 UTC, markmead commented on public/components/marketing-ctas/11.html
> +  <div class="max-w-xl p-12 text-center text-gray-300 sm:p-16 lg:p-24">
Don't need `max-w-xl` and `text-center` should be on the child class.

2022-07-25 06:38 UTC, closed without merging