Toggle buttons
markmead/hyperui pull request #128
Opened 2022-07-30 13:35 UTC by Aniket1026

Below are the changes I made . Here I added to toggle buttons which I think are useful in app or websites to toggle anything in general . If there is something I can improve on or any mistake I made in general  please do tell me . Thank you 😄😄

https://user-images.githubusercontent.com/92184189/181916605-b7cf7cc4-e3ab-4f44-8e46-9a6b1fe3e81a.mp4

2022-07-30 20:03 UTC, markmead commented
Hey @Aniket1026 thanks for this, but I'm not quite sure you understand what HyperUI is. It's a Tailwind CSS component library and therefore components are written with Tailwind CSS.

2022-07-30 20:07 UTC, markmead requested changes

2022-07-30 20:07 UTC, markmead commented on data/components/application-ui-button-groups.mdx
> +  5:
These would be under a new collection called `application-ui-toggles.mdx`.

2022-07-30 20:07 UTC, markmead commented on public/build.css
> -/*! tailwindcss v3.0.23 | MIT License | https://tailwindcss.com*/*,:after,:before{box-sizing:border-box;border:0 solid #e5e7eb}:after,:before{--tw-content:""}html{line-height:1.5;-webkit-text-size-ad
This file is re-compiled on every deployment and therefore any changes would be removed.

2022-07-30 20:07 UTC, markmead commented on public/components/application-ui-button-groups/5.html
> +          </label>
The formatting isn't correct and you haven't used Tailwind CSS.

2022-07-30 20:07 UTC, markmead commented on public/components/application-ui-button-groups/6.html
> +          </label>
The formatting isn't correct and you haven't used Tailwind CSS.

2022-07-31 06:07 UTC, Aniket1026 commented
Sure I'll make changes using tailwind Css . I just started contributing so I was confuse about how to make changes but thanks for telling me .  I'll now  use tailwind to make the same changes 😄

2022-08-01 06:40 UTC, markmead commented
No problem @Aniket1026 I assume that as it's a Tailwind CSS component library it would be obvious, but I'll update the docs.

2022-08-02 06:42 UTC, markmead commented
Rember to re-request my review when you have something @Aniket1026, it looks like a lot of progress has been made!

2022-08-02 07:19 UTC, Aniket1026 commented
Yeahh sure I'll take care of that from now . But I made a slightly different changes as I'm not able to create sun moon toggle button as I suggested instead I added a different toggle .

2022-08-02 11:57 UTC, Aniket1026 commented
@markmead what should I be doing now ? I mean are these changes fine or should I be doing anything else ?

2022-08-02 13:46 UTC, markmead commented
You need to re-request a review as I mentioned 😅
<img width="323" alt="Screenshot 2022-08-02 at 14 46 07" src="https://user-images.githubusercontent.com/50486078/182390113-f28eecbf-ac85-4bfd-98b1-477c16361f0d.png">

2022-08-02 18:39 UTC, Aniket1026 commented
Sorry for the trouble @markmead I was unaware about how to re request review. Thanks for telling and I guess I've requested a review

2022-08-02 19:05 UTC, markmead commented
No worries @Aniket1026 I was a little unsure myself a few months back!

2022-08-02 19:08 UTC, markmead requested changes
Formatting is still off on the component HTML files.

There are some Tailwind CSS changes I'd like to make, if you look at https://play.tailwindcss.com/452s9Bp3Zs this should guide you.

2022-08-02 19:08 UTC, markmead commented on data/components/application-ui-button-groups.mdx
> +
Remove extra line.

2022-08-02 19:08 UTC, markmead commented on data/components/application-ui-toggles.mdx
> +
Remove extra line.

2022-08-02 19:08 UTC, markmead commented on data/components/application-ui-toggles.mdx
> +emoji: ⇌
Should be using an emoji here, could be something like:

- 🎛
- 🎚
- 🕹

It doesn't have to be super accurate to what the collection is.

2022-08-03 04:41 UTC, Aniket1026 commented on data/components/application-ui-button-groups.mdx
> +
Done

2022-08-03 04:48 UTC, Aniket1026 commented
The formatting is done and the new emoji is added . Extra lines are also removed but as for the changes you mentioned for some reason they're not reflecting in on the local host when I tried . So I simply changed the toggle color to green of the rounded toggle .

https://user-images.githubusercontent.com/92184189/182526263-2c465ac2-632c-4721-b73e-36af08522ea9.mp4

when I made the changes they don't seem to be working so the only change I made is change the toggle color of the rounded toggle.

2022-08-03 06:58 UTC, markmead commented
Did you run `yarn watch` while developing or `yarn build` before pushing?

2022-08-03 07:22 UTC, Aniket1026 commented
ok It worked I was not doing running the yarn watch 😅😅

2022-08-03 08:09 UTC, markmead requested changes
Just two very small things to clean up and then we can get this merged! 🥳

2022-08-03 08:09 UTC, markmead commented on public/components/application-ui-toggles/1.html
> +<div class="flex gap-8 p-8">
Sorry, that's my bad, we don't need this line `flex gap-8 p-8`.

2022-08-03 08:09 UTC, markmead commented on public/components/application-ui-toggles/2.html
> +<div class="flex gap-8 p-8">
Once again, we don't need this.

2022-08-03 09:35 UTC, markmead commented
Don't worry about making those changes @Aniket1026, it was my fault so I pulled it down and updated it.

2022-08-03 09:39 UTC, merged

2022-08-03 10:06 UTC, Aniket1026 commented
Hurray 🎉🎉. Really , thanks @markmead . You're a great mentor and I really enjoyed working on this . I learnedso many things in span of 3-4 days with your help 😊. Great experience 😄