Created new marketing pricing collection and new pricing component
markmead/hyperui pull request #338
Opened 2023-07-11 17:43 UTC by usman-faisal

2023-07-12 10:55 UTC, markmead requested changes
Only reviewed one section as the feedback can be applied to more. 

I don't think we need two components that are basically the same, best to decide on one.

2023-07-12 10:55 UTC, markmead commented on public/components/marketing-pricings/1.html
> +                    </svg>
Should be using Heroicons for any icons - https://heroicons.com

2023-07-12 10:55 UTC, markmead commented on public/components/marketing-pricings/1.html
> +        <div class="text-center shadow-sm border border-gray-200 flex flex-col gap-6 sm:p-10 lg:p-12 p-8 rounded-2xl">
Padding is too much on mobile

2023-07-12 10:55 UTC, markmead commented on public/components/marketing-pricings/1.html
> +            <div class="flex flex-col gap-3">
Doesn't need to be using flex

2023-07-12 10:55 UTC, markmead commented on public/components/marketing-pricings/1.html
> +        <div class="text-center shadow-sm border border-gray-200 flex flex-col gap-6 sm:p-10 lg:p-12 p-8 rounded-2xl">
Doesn't need to be using flex

2023-07-12 10:55 UTC, markmead commented on public/components/marketing-pricings/1.html
> +                <p class="text-3xl">Starter</p>
Font is too big on mobile

2023-07-12 10:55 UTC, markmead commented on public/components/marketing-pricings/1.html
> +                    <strong class="text-4xl">20$</strong>
Font is too big on mobile

2023-07-12 10:55 UTC, markmead commented on public/components/marketing-pricings/1.html
> +            <ul class="text-left flex flex-col gap-2">
Doesn't need to be using flex

2023-07-12 10:55 UTC, markmead commented on public/components/marketing-pricings/1.html
> +        <div class="text-center shadow-sm border border-gray-200 flex flex-col gap-6 sm:p-10 lg:p-12 p-8 rounded-2xl">
Shouldn't set the text position here, do it at an element group level

2023-07-12 10:55 UTC, markmead commented on public/components/marketing-pricings/1.html
> +            <a href="#" class="bg-indigo-600 text-white py-4 px-3 rounded self-center">Get Started</a>
Use an existing button style from HyperUI - https://www.hyperui.dev/components/marketing/buttons

2023-07-12 17:12 UTC, usman-faisal commented
I've made the necessary changes, I am using flex in different place to avoid using margin or for spacing and aligning items. Let me know what I can fix/improve next! Thank you so much for your help ♥

2023-07-13 06:57 UTC, usman-faisal commented
> Only reviewed one section as the feedback can be applied to more. 
> 
> 
> 
> I don't think we need two components that are basically the same, best to decide on one.
> 
> 
> 
> ---
> 
> 
> 
> Good work so far, looks nice!

I've made the necessary changes, I am using flex in different place to avoid using margin or for spacing and aligning items. Let me know what I can fix/improve next! Thank you so much for your help ♥

2023-07-13 08:46 UTC, markmead commented
Not all feedback has been addressed as I'd rather see classes like `mt` and `space-y` used instead of `flex` for vertical spacing. It's unnecessary to be using `flex flex-col gap-3` when you can just do `space-y-3`, as an example.

2023-07-13 08:49 UTC, markmead requested changes

2023-07-13 08:49 UTC, markmead commented on public/components/marketing-pricings/1.html
> +                <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffffff" class="w-5 h-5">
Thanks for changing to Heroicons, but `stroke` should be using `currentColor` not a hardcoded value.

2023-07-15 02:45 UTC, usman-faisal commented
Hey! I've made the changes. Also thanks for helping me out on eliminating `flex flex-col gap-3`. Let me know if there are any other possible improvements that can be made ❤

2023-07-15 08:45 UTC, markmead commented
Thanks @usman-faisal, I'll pull down the PR and have a look!

2023-07-15 09:20 UTC, merged

2023-07-15 09:20 UTC, markmead commented
Thanks for working on this @usman-faisal