:sparkles:  Added the first two divider components.
markmead/hyperui pull request #413
Opened 2023-11-09 19:42 UTC by DavidLambauer

2023-11-09 19:43 UTC, DavidLambauer commented
Starting with the two components. Want to add at least left/right-oriented text dividers, too.

2023-11-10 16:44 UTC, markmead requested changes
Looks good! Just a few small changes.

2023-11-10 16:44 UTC, markmead commented on public/components/application-ui-dividers/1.html
> +<div class="flex flex-row items-center max-w-7xl mx-auto">
Safe to remove these classes `flex-row max-w-7xl mx-auto`

2023-11-10 16:44 UTC, markmead commented on public/components/application-ui-dividers/1.html
> +    <span class="w-full flex border-black border-t mr-12"></span>
These could all be `<span>`

2023-11-10 16:44 UTC, markmead commented on public/components/application-ui-dividers/1.html
> +    <div class="w-full flex border-black border-t ml-12"></div>
This could be `flex-1 h-px bg-black`.

2023-11-10 16:44 UTC, markmead commented on public/components/application-ui-dividers/1.html
> +    <span class="w-full flex border-black border-t mr-12"></span>
This could be `flex-1 h-px bg-black`.

2023-11-10 16:44 UTC, markmead commented on public/components/application-ui-dividers/2.html
> +<div class="h-px border-t-0 bg-transparent bg-gradient-to-r from-transparent via-neutral-500 to-transparent opacity-75"></div>
No need for the border classes.

2023-11-10 16:44 UTC, markmead commented on src/data/components/application-ui-dividers.mdx
> +container: py-20 max-w-3xl mx-auto items-center
Maybe `p-6 grid place-content-center`.

2023-11-11 10:28 UTC, markmead requested changes

2023-11-11 10:28 UTC, markmead commented on public/components/application-ui-dividers/1.html
> +    <span class="px-6">more</span>
Be good to put a `shrink-0` on this as well.

2023-11-13 10:34 UTC, DavidLambauer commented
Thx for the comments. Will continue working on it soon! 🥳

2023-11-13 19:45 UTC, DavidLambauer commented
HI @markmead, 

Thank you for the feedback. I'm actually a backend dev and still learning proper FE development. Glad you take the time to review it. 

I guess I addressed your feedback and added two more dividers for left/right alignment. Not sure about the `place-content-center` thing, though. Doesn't seem to have the correct effect.

2023-11-14 16:21 UTC, markmead requested changes
Good stuff! Small changes and then we should be good to go, unless you want to keep add some more?

2023-11-14 16:21 UTC, markmead commented on public/components/application-ui-dividers/1.html
> +    <span class="flex-1 bg-black h-px mr-12"></span>
Think it's OK to remove the margin classes.

2023-11-14 16:21 UTC, markmead commented on public/components/application-ui-dividers/3.html
> +    <span class="px-4">Align Left</span>
Should use `pr` instead of `px` and let's use `pr-6` so it is consistent spacing with the first one.

2023-11-14 16:21 UTC, markmead commented on public/components/application-ui-dividers/3.html
> +    <span class="flex-1 bg-black h-px mr-12"></span>
Can remove the `mr-12`.

2023-11-14 16:21 UTC, markmead commented on public/components/application-ui-dividers/4.html
> +</span>
Same comments as above just applied to this component.

2023-11-14 16:21 UTC, markmead commented on src/data/components/application-ui-dividers.mdx
> +    title: Algin Left
Algin > Align

2023-11-17 16:21 UTC, markmead commented
Any updates for this? @DavidLambauer

2023-11-17 16:22 UTC, DavidLambauer commented
Will work on it tonight. No more dividers planned

2023-11-17 16:32 UTC, DavidLambauer commented
@markmead done 😄 Thanks for the reminder.

2023-11-17 18:27 UTC, markmead approved these changes

2023-11-17 18:28 UTC, merged