Feature - Add sortable table components
markmead/hyperui pull request #479
Opened 2024-07-02 09:43 UTC by ShahStavan

2024-07-02 09:44 UTC, ShahStavan commented
Hi @markmead 
All changes you asked for are done. Please review the code.
Thank You.

2024-07-02 13:16 UTC, markmead requested changes
Shouldn't be `dark:` classes, or `id` attributes, or `onclick` events.

2024-07-03 08:32 UTC, markmead reviewed
Looks good! Just a few comments to address and then we can start the dark and interactive variants! 🎉

2024-07-03 08:32 UTC, markmead commented on public/components/application-ui-tables/8.html
> +            <span class="sort-icon">&uarr;&darr;</span>
I think we should use a chevron here:

```
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="size-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="m19.5 8.25-7.5 7.5-7.5-7.5" />
</svg>
```

Might need some tweaking as `size-6` is pretty large.

2024-07-03 08:32 UTC, markmead commented on public/components/application-ui-tables/8.html
> +            <span class="sort-icon">&uarr;&darr;</span>
No need for the `sort-icon` class either.

2024-07-03 08:32 UTC, markmead commented on src/data/components/application-ui-tables.mdx
> +    dark: false
Can remove this line.

2024-07-06 11:13 UTC, markmead commented
Are you still working on this? @ShahStavan Or do you want me to take a look?

2024-07-08 15:16 UTC, closed without merging