fix/site/toast-gtag-responsive
markmead/hyperui pull request #63
Opened 2022-04-26 05:19 UTC by tianenpang

- [x] fix copied toast
- [x] gtag script warning (next/script)
- [x] responsive mian
- [x] update range when current breakpoint changes
- [x] disable button text selection

2022-04-26 07:33 UTC, markmead requested changes
Looks good! 🎉 There are a few comments, nothing huge!

---

I haven't had much look with `next/script` for Google Tag Manager, but I'll check out how it's doing on the staging link Vercel provided.

There were toast notifications, but I must have left them out in a recent update, here's the [commit where they were last working](https://github.com/markmead/hyperui/tree/464b9670faeb7aa0d4bba79e39a1cc3a6a70cdb8). It would be good to use what was there before, I don't mind making the change if you're OK with me making changes to this PR?

2022-04-26 07:33 UTC, markmead commented on pages/components/[slug].tsx
> +          <div className="prose max-w-full">
Both work but `max-w-none` is the suggested approach, can we use that, please?

2022-04-26 07:33 UTC, markmead commented on styles/button.module.css
> +  @apply inline-flex items-center px-3 py-1.5 border-2 border-black rounded-lg select-none hover:bg-black hover:text-white;
Doesn't need this.

2022-04-26 07:33 UTC, markmead commented on components/component/example.tsx
> +          {!view && (
What's the benefit of this? 🤔

It's handled with the `className` above, feels like an extra step.

2022-04-26 07:33 UTC, markmead commented on components/component/example.tsx
> +  }
Great addition! Thank you! 🙌 

Could it be reformatted like: 

```js
const handleWidth = (width: string) => {
  setWidth(width)

  width === '100%'
    ? setRange(1348)
    : setRange(Number(width.replace('px', '')))
}
```

2022-04-26 13:29 UTC, tianenpang commented
All done 🙌🏻

2022-04-26 14:21 UTC, markmead commented
Awesome, thanks @tianenpang! Are you happy for me to make some changes to bring back in the old toast notifications?

2022-04-26 14:57 UTC, tianenpang commented
Sure, please. I did not find the old toast in the [commit](https://github.com/markmead/hyperui/tree/464b9670faeb7aa0d4bba79e39a1cc3a6a70cdb8) you mentioned 👀

2022-04-26 16:06 UTC, markmead approved these changes
All good! Let's hope that `next/script` change doesn't break the tracking like it did the last time I tried it 😭

Feel free to merge when you see this @tianenpang!

2022-04-26 16:48 UTC, tianenpang commented
I removed the toast style from the globals and the google analytics looks well tracked locally 👀

2022-04-26 17:41 UTC, markmead approved these changes

2022-04-26 22:34 UTC, tianenpang commented
Hey @markmead, I've made some updates for google analytics feature, looks well collected in debug view and works fine in the preview. 👀

Screenshot of analytics debug view

![Screenshot of debug view](https://user-images.githubusercontent.com/32772271/165403168-5cbc3dfc-098e-4e7f-bc6a-9240048809bf.jpg)

2022-04-27 20:39 UTC, tianenpang commented
Looks tracked very well and reverted to the way it was before.

Screenshot of analytics debug view

![analytics debug view](https://user-images.githubusercontent.com/32772271/165626857-86ab109f-5074-4ef0-b2ae-9853c6747697.png)

2022-04-28 11:18 UTC, markmead commented
Awesome! 🥳  Thanks for all the work on this, really appreciated!

2022-04-28 11:18 UTC, merged